# Generated by Django 6.0.6 on 2026-06-12 15:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAuditHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('loan_id', models.UUIDField(db_index=True)),
                ('tenant_id', models.UUIDField()),
                ('officer_id', models.IntegerField(null=True)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(null=True)),
                ('new_value', models.TextField(null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'loan_audit_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nik', models.CharField(db_index=True, max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('land_area_ha', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('commodity', models.CharField(default='rice', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenants.tenant')),
            ],
            options={
                'db_table': 'members',
                'unique_together': {('tenant', 'nik')},
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tenor_months', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('restructured', 'Restructured'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('closed', 'Closed'), ('defaulted', 'Defaulted')], default='pending', max_length=20)),
                ('declared_yield_tons', models.DecimalField(decimal_places=2, max_digits=8)),
                ('commodity', models.CharField(default='rice', max_length=50)),
                ('planting_month', models.IntegerField(help_text='1-12, month when planting starts')),
                ('harvest_month', models.IntegerField(help_text='1-12, expected harvest month')),
                ('monthly_living_cost', models.DecimalField(decimal_places=2, default=2000000, max_digits=12)),
                ('monthly_farming_cost', models.DecimalField(decimal_places=2, default=500000, max_digits=12)),
                ('simulation_result', models.JSONField(blank=True, null=True)),
                ('avs_flag', models.BooleanField(default=False, help_text='Agricultural Verification Score red flag')),
                ('months_in_arrears', models.IntegerField(default=0)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_loans', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='tenants.tenant')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='loans.member')),
            ],
            options={
                'db_table': 'loans',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('savings_deposit', 'Savings Deposit'), ('savings_withdrawal', 'Savings Withdrawal'), ('loan_disbursement', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment'), ('rice_sale', 'Rice Sale'), ('rice_purchase', 'Rice Purchase')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='loans.loan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loans.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
