# Generated by Django 6.0.6 on 2026-06-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('regional_avg_yield_tons_ha', models.DecimalField(decimal_places=2, max_digits=6)),
                ('avg_price_per_kg', models.IntegerField(help_text='IDR per kg')),
            ],
            options={
                'db_table': 'commodities',
            },
        ),
    ]
