# Generated by Django 6.0.6 on 2026-06-13 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        ('tenants', '0002_alter_verification_document_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Masuk / Restock'), ('OUT', 'Keluar / Distribusi')], max_length=3)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_per_kg', models.IntegerField(help_text='IDR per kg at time of transaction')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('logged_at', models.DateTimeField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='logistics.commodity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity_logs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'commodity_logs',
                'ordering': ['-logged_at'],
            },
        ),
    ]
